version: "3.8"
services:
    dysn_gateway:
      container_name: dysn-gateway
      build:
        context: ../.
        dockerfile: .deploy/Dockerfile
      env_file:
        - .env
      networks:
        - dysn
      ports:
        - "8080:8080"
      volumes:
        - dysn_gateway:/var/www/html/dysn/gateway

volumes:
  dysn_gateway:

networks:
  dysn:
    name: dysn